[package]
name = "compare_font"
version = "1.0.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
font-kit = "0.14.2"
